name: Multi-Platform Benchmark

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  benchmark:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: debian
          - os: windows-latest
            platform: windows
          - os: macos-latest
            platform: mac-arm
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up environment
      run: |
        echo "Running on ${{ matrix.platform }}"
        echo "OS: ${{ matrix.os }}"
    
    - name: Make script executable (Unix)
      if: matrix.os != 'windows-latest'
      run: chmod +x ./scripts/bench.sh
    
    - name: Run benchmark script (Unix)
      if: matrix.os != 'windows-latest'
      run: ./scripts/bench.sh
    
    - name: Run benchmark script (Windows)
      if: matrix.os == 'windows-latest'
      run: bash ./scripts/bench.sh
      shell: bash